name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make

      - name: Build test1
        run: make tests

      - name: Run tests
        run:  ./bin/tests

      - name: Build test2
        run: make test2

      - name: Run tests
        run:  ./bin/test_2




